language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  - hhvm-nightly
before_script:
  - composer install
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
