language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: hhvm-nightly
services:
  - redis-server
  - rabbitmq
before_script:
  - phpenv config-add travis-config.ini
  - composer install
