language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
services:
  - redis-server
  - rabbitmq
before_script:
  - phpenv config-add travis-config.ini
  - composer self-update --stable
  - composer update
script:
  - vendor/bin/phpunit --testdox --testsuite "Parallel Task Test Suite"
